### ISSUE TITLE
Develop application UI (front-end) - Register

### ISSUE THREAD

**Issue by Obadha** [Obadha/baraza#5]
Using android studio, create the android application's use interface following the wireframe.

Screens [1.1, 1.2, 1.3 and 1.4](https://github.com/Obadha/baraza/blob/master/APPLICATIONFLOWIMAGE1.jpg)

**Task:** Develop application's register screens.
**Deliverables:** Code pushed to develop branch that's the application's User interface.

**Comment by karimkkanji** [comment]
check out this repo https://github.com/kanji-karanja/BarazaKe and tell me how the user interface is like since the main repo failed to build on my machine

**Comment by Obadha** [comment]
@kanji-karanja done. 
Looks good.
I will make some minor fixes and push to your repo.

I will however strongly suggest we find a way of working on one repo, the main one. That way it will be easier to  collaborate and make changes.
Could you try and get the main repo working? I think all you need is a decent internet connection. Let me know how it goes, and what challenges you face so that I see how I can help.

**Comment by Obadha** [comment]
I'll close this for now since the major work has been done. For modifications or alterations, new issues will be opened.
