### ISSUE TITLE
Develop application UI(front-end) - Login

### ISSUE THREAD

**Issue by Obadha** [Obadha/baraza#8]
Using android studio, create the android application's user interface for the login screen following the wireframe.

Screen [1.5](https://github.com/Obadha/baraza/blob/master/APPLICATIONFLOWIMAGE1.jpg)

**Task:** Develop application's login screen.
**Deliverables:** Code pushed to develop branch that's the application's User interface.

**Comment by valentineMunikah** [comment]
Should the log in page include the type of user(chief or client) as well?

**Comment by karimkkanji** [comment]
check out this repo https://github.com/kanji-karanja/BarazaKe and tell me how the user interface is like since the main repo failed to build on my machine

**Comment by Obadha** [comment]
I'll close this for now since the major work has been done. For modifications or alterations, new issues will be opened.
